### ISSUE TITLE
Disconnects Frequently and Dies (also config update suggestion)

### ISSUE THREAD

**Issue by SenorKarlos** [versx/GuildStats#2]
it died on me April 11th 😅 with a pile of websocket errors, and on restart it took 2-3x to connect. It's still netcore 2.1 and DSharp 3.2.3. It also repeated this yesterday on Apr 30th. While running it keeps doing this.
![image](https://user-images.githubusercontent.com/10344114/166162741-a582622b-8e5b-4812-826e-df09f19d9b67.png)

For the config, I've noticed the main key for each server must be an int, therefore makes sense to use the server ID. That same ID is asked for again in the second subkey. I'd rather be able to use words to identify the main keys and keep that there in the subkeys, or just remove the subkey altogether as it has the number.

**Comment by versx** [comment]
Issue should be resolved.
