### ISSUE TITLE
Rate Limits out the ass

### ISSUE THREAD

**Issue by SenorKarlos** [versx/GuildStats#3]
It was ok with a few channels... now fully implemented... I'm gonna get the token revoked here ;) did this for like 2 mins while connecting to each discord and updating the channels, and I saw it happening earlier in my logs when I did a bunch of mass role assignments
![image](https://user-images.githubusercontent.com/10344114/166238703-f2a1ba58-13e3-4c55-9a5d-f5495e166603.png)

**Comment by SenorKarlos** [comment]
Not sure if this is related, or a different issue
![image](https://user-images.githubusercontent.com/10344114/166620364-d8035fa6-9133-4bea-b0ba-afe3523c72db.png)

**Comment by versx** [comment]
Should be fixed
